spring:
  application.startup: buffering
  main:
    web-application-type: none # HTTP サーバは起動しないため none に設定
  cloud:
    function:
      definition: functionRouter # 常に Router を起動する
spring.cloud.function.routing-expression: pgmid
logging:
  level:
    root: INFO
    org.springframework:
      boot.startup: INFO
